#!/bin/bash
# test-workflow.sh - Script to test the GitHub Actions workflow

# Replace with your actual values
GITHUB_TOKEN="your_github_token_here"
REPO_OWNER="pluricalifornia"
REPO_NAME="plurinational-landreform"

# Test JSON data (properly escaped for curl)
TEST_ORDER_DATA='{
  "timestamp": "2025-01-22T15:30:00.000Z",
  "orderNumber": "TM-TEST-001",
  "organization": {
    "name": "Test Organization",
    "type": "student-cooperative", 
    "contactPerson": "Test User",
    "email": "test@example.com"
  },
  "orderItems": [
    {
      "product": "Kale",
      "quantity": 1,
      "pricing": "individual",
      "itemTotal": 2.00
    }
  ],
  "delivery": {
    "method": "farm-pickup",
    "preferredDate": "2025-01-25"
  },
  "estimatedTotal": 2.00
}'

echo "Testing GitHub Actions workflow..."

# Trigger the workflow via GitHub API
curl -X POST \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Authorization: Bearer $GITHUB_TOKEN" \
  -H "Content-Type: application/json" \
  "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/process-orders.yml/dispatches" \
  -d "{
    \"ref\": \"main\",
    \"inputs\": {
      \"order_data\": $(echo "$TEST_ORDER_DATA" | jq -c .)
    }
  }"

echo "Workflow triggered. Check your repository's Actions tab to see the results."
